### PR TITLE
Added MicroOS profiles

### PR DESCRIPTION
**Pull request by nadvornik**
This implements https://github.com/SUSE/spacewalk/issues/14570

It depends on Kiwi --profile option feature, which will be available in SUSE Manager 4.2.2
https://github.com/SUSE/spacewalk/issues/9264

### CODE REVIEW

**Comment by aaannz** [comment]
Hmm... right. I don't like it, but I don't know how to solve it. 🤷🏾‍♂️ 

This is basically forking it even though we did not want to do that. Who will update the profiles here when the source is updated? I tried to find if MicroOS is developed somewhere in git, but couldn't find it. Only in OBS.

Any ideas? @jsrain @gmoro

Btw. @nadvornik this is still without saltboot integration, right?

**Comment by nadvornik** [comment]
I don't think we need saltboot here. These are the same images as in OBS, so the customers can use it as a base for their development.

**Comment by aaannz** [comment]
> I don't think we need saltboot here. 

Why do you think so? On call with a customer a possibility to pxe deploy k3s was considered as an option. I understand it is not expected to have it right now, but as a future development?

> These are the same images as in OBS, so the customers can use it as a base for their development.

Exactly. So who will update this git repo when image in OBS will change?

**Comment by nadvornik** [comment]
The images here are expected to be tested, so I don't think we can update it automatically. I think that every update will need an issue on SUMA and will be done by the asignee of that issue.

Saltboot support is a new feature, it can be added as an extra profile, first in OBS and then copied here.

**Comment by aaannz** [comment]
> The images here are expected to be tested, so I don't think we can update it automatically. I think that every update will need an issue on SUMA and will be done by the asignee of that issue.

So basically waiting for bug reports.
If there will not be any automation, then for any bugreport against MicroOS JeOS fixed by upstream we will eventually have bug report against our templates and only after then we will fix it here. Is that the plan? I expect profiles in OBS to be already tested.

> Saltboot support is a new feature, it can be added as an extra profile, first in OBS and then copied here.

I agree.

**Comment by nadvornik** [comment]
> I expect profiles in OBS to be already tested.
The environment in SUMA is different than in OBS. During testing, the profiles which were OK in OBS failed in SUMA because of problems with SSL certificates and because of packages missing in SCC. This can happen again.

**Comment by aaannz** [comment]
> The environment in SUMA is different than in OBS. During testing, the profiles which were OK in OBS failed in SUMA because of problems with SSL certificates and because of packages missing in SCC. This can happen again.

Yes and that is bug report against SUMA image building. And this is git. If needed, can still be reverted to previous version.

**Comment by nadvornik** [comment]
I have synced it with current version from Build Service.
@mbologna Can you please merge it?

**Pull request merged**
