### PR TITLE
Add kiwi-desc-saltboot requirement

### PR DESCRIPTION
**Pull request by aaannz**

### CODE REVIEW

**Comment by mbologna** [comment]
Maybe we can also add in which repo `kiwi-desc-saltboot`?

**Comment by aaannz** [comment]
The repo is internal only. This remark can be left here even when `kiwi-desc-saltboot` is released.

**Comment by abhinav-puri** [comment]
It may help to add the following statement:

The `kiwi-desc-saltboot` package, as well as the reference templates for POS images, will be made available in the Manager:Tools channel with the release of SUSE Manager for Retail 3.2.

Thoughts? @mbologna @aaannz @joesusecom @kkaempf

**Comment by kkaempf** [comment]
@aaannz please add a reasonable description

- what is `kiwi-desc-saltboot` ?

If it's a package, where is it needed ?
If on the server, then it needs to go into Manager-Update
If on the client, then it needs to go into Manager-Tools

In any case, please get in contact with @juliogonzalez

**Comment by aaannz** [comment]
@kkaempf  This it nothing new, there is already approved ECO for this and issue https://github.com/SUSE/spacewalk/issues/5202 which I planned to do this sprint, but was postponed due to running MU.

**Comment by abhinav-puri** [comment]
@kkaempf 

This is related to the following issue: https://github.com/SUSE/spacewalk/issues/5202

**Comment by mbologna** [comment]
To summarize:
to build the public example profile here the customer needs to have `kiwi-desc-saltboot` installed in the OS Image build host.
Until the package will be published in Manager:Tools (because it's needed on the client), the package lives inside an internal repo: Devel:SLEPOS:SUSE-Manager-Retail:Head
How can the customer install `kiwi-desc-saltboot` if the package is installable only from an internal repo?

**Comment by aaannz** [comment]
> How can the customer install kiwi-desc-saltboot if the package is installable only from an internal repo?

They cannot. Customer can build images of other boot types - oem, iso, containers I guess. Just not the saltboot one. Customer can even build netboot based images used in previous SLEPOS/SMR3.1 product. Some of the boot types is a subject of installing corresponding `kiwi-desc-*` packages available on SLES12SP3 system:
```bash
> zypper se kiwi-desc-*
Loading repository data...
Reading installed packages...

S | Name              | Summary                                          | Type
--+-------------------+--------------------------------------------------+--------
  | kiwi-desc-isoboot | KIWI - Live ISO boot templates                   | package
  | kiwi-desc-netboot | KIWI - PXE network boot templates                | package
  | kiwi-desc-oemboot | KIWI - Expandable Virtual Machine boot templates | package
  | kiwi-desc-vmxboot | KIWI - Virtual Machine boot templates            | package
```

For e.g. Tumbleweed provided Uyuni, boot type descriptions are in package `kiwi-boot-descriptions`

It is true, that for these other boot types there are no examples in this repository. As an experiment, JeOS templates can be taken from OBS, but who will then maintain these examples?

**Comment by abhinav-puri** [comment]
If there is no way that the customer can install the `kiwi-desc-saltboot` package, and the customer can only build images for other boot types, then it should be documented that this feature is unsupported at the moment.

We can only support images as long as they are based on the POS-* templates.

**Comment by mbologna** [comment]
I agree with @abhinav-puri and I think we should rephrase the message presented in the README.

**Comment by aaannz** [comment]
Ok, I updated readme with disclaimer and also added note about image deployment.

**Comment by mbologna** [comment]
Feel free to merge, thanks!

**Comment by aaannz** [comment]
@mbologna Thanks for review, I however can't merge. Seems like I lack some permissions.

**Pull request merged**
