### PR TITLE
Use salt bundle

### PR DESCRIPTION
**Pull request by nadvornik**
Switch to salt bundle in OS images.

Note: this must be merged after the new dracut-saltboot is released.

### CODE REVIEW

**Comment by aaannz** [comment]
Now it got me thinking, I did not plan to release salt bundled saltboot for SUMA4.2, but these templates are universal across SUMA/Uyuni versions.
Should we release dracut-saltboot for 4.2 as well or rather create new branch (4.2 and even 4.1) or new templates (e.g. v7.1.0, v6.1.0) ?

**Comment by nadvornik** [comment]
I don't see any  problem in releasing dracut-saltboot for 4.2

**Comment by aaannz** [comment]
Not yet. Neither 4.3.2 nor 4.2.9 was released yet and only in those versions dracut-saltboot and kiwi-desc-saltboot have support for salt bundle.

**Comment by aaannz** [comment]
We forgot about this, now all things are in place so this can be merged. @mbologna can I ask you for merge?

**Pull request merged**
